### ISSUE TITLE
Tests fail due to navigation

### ISSUE THREAD

**Issue by almasaeed2010** [statonlab/WoodRef#12]
The navigation component makes tests fail for some reason.

```js
FAIL  __tests__/App-test.js
  ● Console

    console.error node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9036
      The above error occurred in the <Navigator> component:
          in Navigator (created by Context.Consumer)
          in ThemeProvider (created by Context.Consumer)
          in withTheme(Navigator)
      
      Consider adding an error boundary to your tree to customize error handling behavior.
      Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

  ● renders correctly

    TypeError: Cannot read property 'Direction' of undefined

      at Object.Direction (node_modules/react-native-gesture-handler/Directions.js:3:39)
      at Object.<anonymous> (node_modules/react-native-gesture-handler/GestureHandler.js:20:1)
```

**Comment by almasaeed2010** [comment]
fixed,
